pipeline {
    agent any
    
	stages {
        stage ('Getting prerequisites'){
            steps {
                sh 'curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
            }
        }
        stage ('Building application image'){
            steps {
                sh 'docker build -t aplic_java2 -f Dockerfile .'

            }
        }
        stage ('Compose Up Stage'){                
            steps {
                sh 'chmod 777 docker-compose.yml' 
                sh 'docker-compose -f /home/brenomartins/Teste/docker-compose.yml up -d'
                sleep(5)
            }
        }
        stage ('Setting BD'){
            steps {
                withCredentials ([string(credentialsId: 'senha', variable: 'SENHA')]){
                    sh 'sudo PGPASSWORD=$SENHA psql    --host=localhost    --port=5555    --username=postgres --no-password  --file acesso_init.sql'
                }
            }
        }
    }
}
