version: '3.5'

services:   
   aplication:
      image: aplic_java2
      networks:
         appnetwork:
            ipv4_address: 172.38.1.1
      environment:
      - PORT=5432
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - HOST=172.38.1.2
      - DBNAME=postgres
      - DATASOURCE_URL=jdbc:postgresql://172.38.1.2:5432/postgres
      ports:
      - "9094:9095"
      depends_on:
      - bd-postgres

   bd-postgres:
      image: postgres
      networks:
         appnetwork:
            ipv4_address: 172.38.1.2
      environment:
      - POSTGRES_PASSWORD=postgres
      ports:
      - "5555:5432"

networks:
   jenkins_default:
      external: 
         name: jenkins_default