version: '3.5'

services:   
   aplication:
      image: aplic_java2
      container_name: application
      networks:
         default:
      environment:
      - PORT=5432
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - HOST=bd-postgres
      - DBNAME=postgres
      - DATASOURCE_URL=jdbc:postgresql://bd-postgres:5432/postgres
      ports:
      - "9094:9095"
      depends_on:
      - bd-postgres

   bd-postgres:
      image: postgres
      container_name: postgres
      networks:
         default:
      environment:
      - POSTGRES_PASSWORD=postgres
      ports:
      - "5432:5432"

networks:
   default:
      external: 
         name: netjenkins