version: '3.5'

services:   
   aplication:
      image: aplic_java2
      # networks:
      #    appnetwork:
      #       ipv4_address: 172.38.1.1
      environment:
      - PORT=5432
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - HOST=172.38.1.2
      - DBNAME=postgres
      - DATASOURCE_URL=jdbc:postgresql://172.38.1.2:5432/postgres
      ports:
      - "9094:9095"
      command:  "echo TESTANDO && psql    --host=bd-postgres    --port=5432   --username=postgres --no-password  --file acesso_init.sql"
      depends_on:
      - bd-postgres
      links:
      - bd-postgres

   bd-postgres:
      image: postgres
      # networks:
      #    appnetwork:
      #       ipv4_address: 172.38.1.2
      environment:
      - POSTGRES_PASSWORD=postgres
      ports:
      - "5555:5432"

# networks:
#    appnetwork:
#       name: appnetwork
#       ipam:
#          driver: default
#          config:
#             - subnet: 172.38.0.0/16