version: '3.5'

services:   
   sonar:
      image: sonarqube
      container_name: sonarqube
      networks:
         default:

      environment:
      - sonar.jdbc.url=jdbc:postgresql://bd-postgres:5432/postgres
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=sonar=postgres
      ports:
      - "9000:9000"

networks:
   default:
      external: 
         name: netjenkins
