pipeline {
    agent any
    
	stages {
        stage ('Application Down Stage'){
            steps {
                // sh 'docker-compose --project-directory /var/jenkins_home/workspace/Aplication-Up down'
                // sh 'docker-compose down'
                sh 'docker ps'
                sh 'docker stop aplication-up_aplication_1 aplication-up_bd-postgres_1'
                sh 'docker rm aplication-up_aplication_1 aplication-up_bd-postgres_1'
                sh 'docker ps -a'
            }
        }
    }
}
