pipeline {
    agent any
    
	stages {
        stage ('Checkout'){
            steps {
                git url: 'https://github.com/brenomartins-ciandt/Jenkins-rep.git'
            }
        }
        stage ('Compose Stage'){
            steps {
                sh 'docker-compose -f docker-compose.yml stop'
                sh 'docker-compose -f docker-compose.yml down'
            }
        }
    }
}
