pipeline {
    agent any
    
	stages {
        stage ('Checkout'){
            steps {
                git url: 'https://github.com/brenomartins-ciandt/Jenkins-rep.git'
            }
        }
        stage ('Compose Stage'){
            steps {
                sh 'docker network disconnect -f appnetwork application-up_aplication_1'
                sh 'docker network disconnect -f appnetwork application-up_bd-postgres_1'
                sh 'docker network rm appnetwork'
                sh 'docker stop application-up_aplication_1 application-up_bd-postgres_1'
                sh 'docker rm application-up_aplication_1 application-up_bd-postgres_1'
            }
        }
    }
}
