version: '3.5'

services: 
   jenkinscontainer:
      image: jenkinsnew
      ports:
      - 8080:8080
      - 50000:50000
      networks:
         default:
      volumes: 
      - "/home/brenomartins/Jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      user: root

networks:
   default:
      name: netjenkins

