version: '3.5'

services: 
   jenkinscontainer:
      image: jenkinsnew
      ports:
      - 8080:8080
      networks:
         jenkins_default:
            # ipv4_address: 172.38.1.3
     #- "50000:50000"
      volumes: 
      - "/home/brenomartins/Jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      user: root
#--rm

networks:
   jenkins_default:
      name: jenkins_default
      ipam:
         driver: default
         config:
            - subnet: 172.38.0.0/16

