version: '3.5'

services: 
   jenkinscontainer:
      image: jenkinsnew
      ports:
      - 8080:8080
      - 50000:50000
      networks:
         jenkins_default:
      volumes: 
      - "/home/brenomartins/Jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      user: root
#--rm

networks:
   jenkins_default:
      name: jenkins_default

